---
title: Agustin N. R. Ramirez
description: Working on a better version of myself ğŸ’ªğŸ½ and everyday learning everything related to Javascript, Node, React and React Native.
domain: https://agustin107.github.io
language: es
email: agustin.n.r.ramirez@gmail.com
social:
  twitter: agustin107
  github: agustin107
  npm: agustin107
  linkedin: ramirezagustin
incremental: false # Change to `true` if your server support keeping `.cache` and `public` folders
